//Promise method
// var promise = new Promise(function(resolve,reject){
//     var str1 = 'Helloworld'
//     var str2 = 'Helloworld'
//      if(str1===str2){
//         resolve();
//      }else{
//         reject();
//      }
// });
// promise.then(function(){
//     console.log('Your resolve is Helloworld Success')
// }).catch(function(){
//     console.log('Condition false its is Reject method')
// })

var Name = 'Pramod'
console.log(Name)
console.log(`my name is ${Name}`)

// Arrow functiin
function abc(){
    console.log('hello paniem leda niku');
}
abc()
let pani = ()=>console.log(pani())
